// src/State/Address/ActionTypes.js
// export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
// export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
// export const UPDATE_ADDRESS_FAILURE = "UPDATE_ADDRESS_FAILURE";
// export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
// export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
// export const DELETE_ADDRESS_FAILURE = "DELETE_ADDRESS_FAILURE";

// ActionType.js

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAILURE = "UPDATE_ADDRESS_FAILURE";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILURE = "DELETE_ADDRESS_FAILURE";

export const FETCH_ADDRESSES_REQUEST = "FETCH_ADDRESSES_REQUEST";
export const FETCH_ADDRESSES_SUCCESS = "FETCH_ADDRESSES_SUCCESS";
export const FETCH_ADDRESSES_FAILURE = "FETCH_ADDRESSES_FAILURE";

export const FETCH_USER_ADDRESSES_REQUEST = "FETCH_USER_ADDRESSES_REQUEST";
export const FETCH_USER_ADDRESSES_SUCCESS = "FETCH_USER_ADDRESSES_SUCCESS";
export const FETCH_USER_ADDRESSES_FAILURE = "FETCH_USER_ADDRESSES_FAILURE";
